import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from './components/NavigationBar';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body className="flex flex-col min-h-screen m-0 p-0">
        <NavigationBar />
        <main className="flex-grow p-4">
          {children}
        </main>
      </body>
    </html>
  );
}
